### ISSUE TITLE
Any plan to support nodeJS?

### ISSUE THREAD

**Issue by hoppingninja666** [overlookmotel/google-drive-uploader#16]
I can't use this library with nodeJS. I get this following error
`ReferenceError: document is not defined`

**Comment by overlookmotel** [comment]
It is meant to work with NodeJS. It used to, but evidently something has broken recently.

This package sadly does not have any tests as present, as I couldn't figure out how to test it properly without hitting Google APIs repeatedly and running up a bill.

Can you give a code example which causes this error please?

**Comment by overlookmotel** [comment]
Also, what version of Node are you on please?

**Comment by hoppingninja666** [comment]
I stumbled onto this error in nodeJS version `v10.20.1`. Simply requiring this package returns this error. I am pasting the node REPL shell output here.

`> require('google-drive-upload')
Thrown:
ReferenceError: document is not defined
    at /app/node_modules/google-drive-upload/lib/index.js:1:26510
    at /app/node_modules/google-drive-upload/lib/index.js:1:26465
    at /app/node_modules/google-drive-upload/lib/index.js:1:26486
    at n (/app/node_modules/google-drive-upload/lib/index.js:1:382)
    at /app/node_modules/google-drive-upload/lib/index.js:1:26416
    at /app/node_modules/google-drive-upload/lib/index.js:1:69`

**Comment by hoppingninja666** [comment]
I'm sorry, upon close inspection, turns out I have been using a different package, it was `google-drive-upload`

**Comment by hoppingninja666** [comment]
I think there is a typo in the `README.md` file that lead me to this error. On the first code example you have the following line
`const upload = require('google-drive-upload');`

As a result I installed `google-drive-upload` instead of `google-drive-uploader`

**Comment by overlookmotel** [comment]
Doh! How stupid of me. I've rectified the typo now. Thanks for bringing it to my attention and sorry it caused you a faff.
