### ISSUE TITLE
upload files from url

### ISSUE THREAD

**Issue by rexdevin8** [overlookmotel/google-drive-uploader#26]
Is there any way to upload a big file from url to google drive as chunks ( Im trying to make Direct link to google drive uploader app in heroku)

**Comment by overlookmotel** [comment]
This facility is not provided out of the box, but you could do it using the `streamFactory` option.

Provide a custom `streamFactory` which creates a stream from the external HTTP source (using e.g. Axios). This package will take over from there to pipe it up to Google Drive.

Please see the docs [here](https://github.com/overlookmotel/google-drive-uploader#uploading-from-another-data-source).
